### PR TITLE
modified JLC importer to create one library per component

### PR DESCRIPTION
**Pull request by napowderly**

### CODE REVIEW

**Comment by TousstNicolas** [comment]
Hi, thank you for your contribution.

Looks good to me, works as expected.

**Comment by napowderly** [comment]
Thanks! I found there was a bug that adding multiple parts to the same library would create mismatch bracketing errors. Might me a more elegant way to do this, but it did solve the problem for me.

**Comment by TousstNicolas** [comment]
Was it the same issue as mentioned in #30 ? It was caused by a bad substitution in the kicad_sym when trying to add other components.

**Comment by napowderly** [comment]
Yeah seems to be the same problem.

**Pull request merged**
